[package]
name = "youtrack-mcp-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# youtrack api
youtrack-client-wrapper = { workspace = true }

# mcp sdk
rmcp = { workspace = true, features = ["macros", "server", "transport-io"]}

# serde
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
schemars = { workspace = true, default-features = true }